/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Title: Robot from the series "Love death and robots"
*/

import React, { useEffect, useRef, useState } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function NewAvatar(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/robot_from_the_series_love_death_and_robots.glb')
  
  const [bonesReady, setBonesReady] = useState(false)
  
  // Başlangıç rotasyonunu hafızada tutalım
  const initialRotation = useRef(new THREE.Euler())
  const initialSpineRotation = useRef(new THREE.Euler())

  useEffect(() => {
    // Doğrudan useGLTF ile gelen orijinal kemikleri kullanıyoruz
    if (nodes.Head_02 && nodes.spina_01) {
        initialRotation.current.copy(nodes.Head_02.rotation);
        initialSpineRotation.current.copy(nodes.spina_01.rotation);
        setBonesReady(true);
    }
  }, [nodes]);

  // Küresel Fare Hareketi Takibi (UI elementleri engellemesin diye window seviyesinde dinliyoruz)
  const mouse = useRef({ x: 0, y: 0 });
  useEffect(() => {
    const handleMouseMove = (e) => {
       mouse.current.x = (e.clientX / window.innerWidth) * 2 - 1;
       mouse.current.y = -(e.clientY / window.innerHeight) * 2 + 1;
    };
    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  useFrame((state, delta) => {
    // 1. Robotun bütününe ufak bir nefes alma/süzülme hareketi verelim (canlı hissettirsin)
    if (group.current) {
        group.current.position.y = -2.8 + Math.sin(state.clock.elapsedTime * 1.5) * 0.05;
    }

    // 2. Kafa ve Gövde takibi (mouse cursor location)
    const { x, y } = mouse.current; // Global listener koordinatları
    
    if (bonesReady && nodes.Head_02 && nodes.spina_01) {
        // Açı oranlarını uyguladıktan sonra, kafanın fiziksel sınırları aşmasını engellemek için Clamp (Sınırlandırma) ekliyoruz.
        const rawTargetRotX = initialRotation.current.x - (y * 0.5); // Yukarı/Aşağı 
        const rawTargetRotY = initialRotation.current.y + (x * 0.8); // Sağa/Sola
        const rawTargetRotZ = initialRotation.current.z - (x * 0.2); // Çok yatmaması için Z katsayısı düşürüldü
        
        // Boyun kırılmasını kesin olarak önleyen fiziksel sınırlar (Radyan cinsinden maksimum sapma)
        // Arkaya yatmayı (-0.05) seviyesine kilitleyerek neredeyse tamamen sıfırladık. Z boyun bükülmesini iptal ettik.
        const targetRotX = THREE.MathUtils.clamp(rawTargetRotX, initialRotation.current.x - 0.05, initialRotation.current.x + 0.15);
        const targetRotY = THREE.MathUtils.clamp(rawTargetRotY, initialRotation.current.y - 0.4, initialRotation.current.y + 0.4);
        const targetRotZ = THREE.MathUtils.clamp(rawTargetRotZ, initialRotation.current.z - 0.02, initialRotation.current.z + 0.02);
        
        nodes.Head_02.rotation.x = THREE.MathUtils.lerp(nodes.Head_02.rotation.x, targetRotX, 0.1); 
        nodes.Head_02.rotation.y = THREE.MathUtils.lerp(nodes.Head_02.rotation.y, targetRotY, 0.1); 
        nodes.Head_02.rotation.z = THREE.MathUtils.lerp(nodes.Head_02.rotation.z, targetRotZ, 0.1); 
        
        // Vücut/bel kemiğini (Spine) daha hafif döndür
        const rawTargetSpineX = initialSpineRotation.current.x - (y * 0.2); 
        const rawTargetSpineY = initialSpineRotation.current.y + (x * 0.3); 
        const rawTargetSpineZ = initialSpineRotation.current.z - (x * 0.1); 
        
        // Gövdenin aşırı esnemesini önleyen fiziksel sınırlar
        const targetSpineX = THREE.MathUtils.clamp(rawTargetSpineX, initialSpineRotation.current.x - 0.15, initialSpineRotation.current.x + 0.15);
        const targetSpineY = THREE.MathUtils.clamp(rawTargetSpineY, initialSpineRotation.current.y - 0.25, initialSpineRotation.current.y + 0.25);
        const targetSpineZ = THREE.MathUtils.clamp(rawTargetSpineZ, initialSpineRotation.current.z - 0.05, initialSpineRotation.current.z + 0.05);
        
        nodes.spina_01.rotation.x = THREE.MathUtils.lerp(nodes.spina_01.rotation.x, targetSpineX, 0.08); 
        nodes.spina_01.rotation.y = THREE.MathUtils.lerp(nodes.spina_01.rotation.y, targetSpineY, 0.08); 
        nodes.spina_01.rotation.z = THREE.MathUtils.lerp(nodes.spina_01.rotation.z, targetSpineZ, 0.08); 
    }
  });

  return (
    // Robot saf modelinde sağa dönük olduğu için, onu kameraya/kullanıcıya (ve hafifçe sola, yazıya doğru) bakması için Y ekseninde -Math.PI / 2.2 kadar çeviriyoruz.
    <group ref={group} {...props} dispose={null} position={[0, -2.8, 0]} scale={0.35} rotation={[0, -Math.PI / 2.2, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="13b38b2398744f4295b469a8c9d906d1fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Empty" position={[2.458, 0, -102.215]} rotation={[0, 0, Math.PI / 2]} />
                <group name="Kosti" position={[13.777, 460.07, -5.148]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_9" />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Material} skeleton={nodes.Object_10.skeleton} castShadow receiveShadow />
                  </group>
                </group>
                <group name="Empty001" position={[13.138, 0.369, 88.479]} rotation={[0, 0, -Math.PI / 2]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

// Preload disabled to improve initial page load speed
// useGLTF.preload('/robot_from_the_series_love_death_and_robots.glb')
